### PR TITLE
Problems-Controller

### PR DESCRIPTION
**Pull request by alekosittner**
I implemented all of the CRUDs but not the routes

### CODE REVIEW

**Comment by Tyson27** [comment]
checked - All good @alekosittner

**Review by Tyson27 — CHANGES_REQUESTED** [review]
change line 33 remove comment + add resources in routes.rb

**Review by Tyson27 — APPROVED** [review]

**Review by recasique — COMMENTED** [review]
Nice work! 👍🏻 please be more specific in what you did since I almost forgot you also added routes :)

**Review by Charl-e — APPROVED** [review]

**Comment by Charl-e** [comment]
all good, lets move on

**Pull request merged**
