### PR TITLE
associations-validations-form inputs

### PR DESCRIPTION
**Pull request by Tyson27**
Created associations
validations
form input

### CODE REVIEW

**Review by alekosittner — APPROVED** [review]

**Review by recasique — COMMENTED** [review]
you missed an end, apart from that all great

**Review by Charl-e — APPROVED** [review]
Looks good to me

**Review by Tyson27 — COMMENTED** [review]
thanks, I added an end

**Comment by Tyson27** [comment]
Toni had the following comments:
you have the belongs_to :user in the problems controller, but it needs to go in the problem.rb model
instead of the validates :user, presence: true
and in the sign up form, please remove the autofocus true from all of the input fields, you only need it in the first one

**Pull request merged**
