### PR TITLE
Landingpage create

### PR DESCRIPTION
**Pull request by alekosittner**
fixing problems with Toni (.env , Controller, Views, Javascript) and also creating buttons and the background

### CODE REVIEW

**Review by Charl-e — APPROVED** [review]
looking good!

**Review by Charl-e — APPROVED** [review]
approved!

**Comment by Tyson27** [comment]
All good! thanks

**Review by recasique — APPROVED** [review]
Toni's corrections

**Review by Tyson27 — APPROVED** [review]

**Review by Tyson27 — APPROVED** [review]

**Pull request merged**
